Web Development Course
sainingo/Web-Development-Course pull request #1
Opened 2022-03-14 10:39 UTC by sainingo

# Web Development Course _>_ First Capstone Project.
> This is the first Capstone project and I will be building a Web Development course.
1. Set up initialized and ready to rock...

2022-03-16 23:22 UTC, Hamzaoutdoors requested changes
Hey @sainingo, I am **Hamza** your reviewer for this PR 😸 

_You did a great job, I really enjoyed surfing on your fancy website 😄_ 

There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://media.giphy.com/media/42AFvimyQTNQW44PNG/giphy.gif)

## To Highlight
✔️ The repo looks professional
✔️ There are no linter errors
✔️ You have a descriptive README
✔️ Wonderful UI design and good choice of theme🥇 
✔️ You used JavaScript to display dynamically the list of Participants 

Cheers and Happy coding!👏👏👏

## Required Changes ♻️

_See the inline comments below for more required changes 😃_  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
**N.A**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @hamzaoutdoors in your question so I can receive the notification ^_^

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 23:22 UTC, Hamzaoutdoors commented on about.html
> +            </nav>
- [ ] Good job implementing the navbar in your mobile version, but currently I can't navigate to the `home page` using the navbar menu as you can see in the screenshot below, Kindly fix this issue

![navbar_issue](https://user-images.githubusercontent.com/80895497/158706800-c15ace37-7bb3-4773-8767-94c129d953d5.png)

2022-03-16 23:22 UTC, Hamzaoutdoors commented on index.html
> +                </nav>
- [ ] Could you please make the navbar items in the center following the cross axis, you can achieve that by giving `justify-content: center;`

![links](https://user-images.githubusercontent.com/80895497/158707100-1ccabc6b-3ad1-44ac-83e3-3c7a4a66879a.PNG)

2022-03-17 07:03 UTC, sainingo commented
Hi @Hamzaoutdoors 
I made the changes required. Thanks

2022-03-17 07:27 UTC, elyor-doniyorov approved these changes
Hi @sainingo, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-03-20 10:18 UTC, merged